name: Docs CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint-markdown:
    name: Lint Markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: "**/*.md"
          config: |
            {
              "default": true,
              "MD013": false,
              "MD033": false,
              "MD041": false
            }
